
server:
  port: 8023
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: maa
      username: root
      password: 123456
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    listener:
      simple:
        acknowledge-mode: manual
          #并发消费者初始化值
        concurrency: 1
          #并发消费者的最大值
        max-concurrency: 1
        retry:
          enabled: true #是否支持重试



